
import  { getServerSession }  from 'next-auth/next';
import { authOptions } from './api/auth/[...nextauth]/route'
import { redirect } from 'next/navigation';
import Post from './components/post';



export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}


export default async function Home() {

  const session = await getServerSession(authOptions);

  if(!session?.user){
    redirect("/login?callbackUrl=/")
  }


  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <div className='text-black'>{JSON.stringify(session?.user)}</div>
      <div>
        <Post/>
      </div>
    </main>
  )
}








