import  getServerSession  from 'next-auth/next';
import { authOptions } from './api/auth/[...nextauth]/route'
import { redirect } from 'next/navigation';



export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}


export default async function Home() {

  const session = await getServerSession(authOptions)

  if(session){
    redirect("/login?callbackUrl=/")
  }

  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <pre className=''>{JSON.stringify(session?.user)}</pre>
      <div>sxsxsx</div>
    </main>
  )
}








